#
# Copyright (C) 2005-2014 Darron Broad
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# 3. Neither the name `Darron Broad' nor the names of any contributors
#    may be used to endorse or promote products derived from this
#    software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

build:
	cd chipKITPi		&& $(MAKE)
	cd debug		&& $(MAKE)
	cd dsPIC33FJ128GP802	&& $(MAKE)
	cd include		&& $(MAKE)
	cd mouse		&& $(MAKE)
	cd pic16f627		&& $(MAKE)
	cd pic16f648a		&& $(MAKE)
	cd pic16f84a		&& $(MAKE)
	cd pic18f1320		&& $(MAKE)
	cd pic18f2550		&& $(MAKE)
	cd pic18f25k22		&& $(MAKE)
	cd PIC24FJ64GA002	&& $(MAKE)
	cd PIC32MX150F128B	&& $(MAKE)
	cd rkp28sb		&& $(MAKE)
	cd test			&& $(MAKE)
	cd util			&& $(MAKE)
	cd velleman		&& $(MAKE)

install:
	cd chipKITPi		&& $(MAKE) install
	cd debug		&& $(MAKE) install
	cd dsPIC33FJ128GP802	&& $(MAKE) install
	cd include		&& $(MAKE) install
	cd mouse		&& $(MAKE) install
	cd pic16f627		&& $(MAKE) install
	cd pic16f648a		&& $(MAKE) install
	cd pic16f84a		&& $(MAKE) install
	cd pic18f1320		&& $(MAKE) install
	cd pic18f2550		&& $(MAKE) install
	cd pic18f25k22		&& $(MAKE) install
	cd PIC24FJ64GA002	&& $(MAKE) install
	cd PIC32MX150F128B	&& $(MAKE) install
	cd rkp28sb		&& $(MAKE) install
	cd test			&& $(MAKE) install
	cd util			&& $(MAKE) install
	cd velleman		&& $(MAKE) install

uninstall:
	cd chipKITPi		&& $(MAKE) uninstall
	cd debug		&& $(MAKE) uninstall
	cd dsPIC33FJ128GP802	&& $(MAKE) uninstall
	cd include		&& $(MAKE) uninstall
	cd mouse		&& $(MAKE) uninstall
	cd pic16f627		&& $(MAKE) uninstall
	cd pic16f648a		&& $(MAKE) uninstall
	cd pic16f84a		&& $(MAKE) uninstall
	cd pic18f1320		&& $(MAKE) uninstall
	cd pic18f2550		&& $(MAKE) uninstall
	cd pic18f25k22		&& $(MAKE) uninstall
	cd PIC24FJ64GA002	&& $(MAKE) uninstall
	cd PIC32MX150F128B	&& $(MAKE) uninstall
	cd rkp28sb		&& $(MAKE) uninstall
	cd test			&& $(MAKE) uninstall
	cd util			&& $(MAKE) uninstall
	cd velleman		&& $(MAKE) uninstall

clean:
	cd chipKITPi		&& $(MAKE) clean
	cd debug		&& $(MAKE) clean
	cd dsPIC33FJ128GP802	&& $(MAKE) clean
	cd include		&& $(MAKE) clean
	cd mouse		&& $(MAKE) clean
	cd pic16f627		&& $(MAKE) clean
	cd pic16f648a		&& $(MAKE) clean
	cd pic16f84a		&& $(MAKE) clean
	cd pic18f1320		&& $(MAKE) clean
	cd pic18f2550		&& $(MAKE) clean
	cd pic18f25k22		&& $(MAKE) clean
	cd PIC24FJ64GA002	&& $(MAKE) clean
	cd PIC32MX150F128B	&& $(MAKE) clean
	cd rkp28sb		&& $(MAKE) clean
	cd test			&& $(MAKE) clean
	cd util			&& $(MAKE) clean
	cd velleman		&& $(MAKE) clean
	rm -f *~
