#
# Velleman K8048 Programmer for FreeBSD and others.
#
# Copyright (c) 2005-2013 Darron Broad
# All rights reserved.
#
# Licensed under the terms of the BSD license, see file LICENSE for details.
#
# REQUIRES: gpasm gEDA gEDA-utils
#
build:
	cd debug       && $(MAKE)
	cd include     && $(MAKE)
	cd microchip   && $(MAKE)
	cd mouse       && $(MAKE)
	cd pic16f627   && $(MAKE)
	cd pic16f648a  && $(MAKE)
	cd pic18f1320  && $(MAKE)
	cd pic18f2550  && $(MAKE)
	cd pic18f25k22 && $(MAKE)
	cd pic30       && $(MAKE)
	cd rkp28sb     && $(MAKE)
	cd test        && $(MAKE)
	cd velleman    && $(MAKE)

install:
	cd debug       && $(MAKE) install
	cd include     && $(MAKE) install
	cd microchip   && $(MAKE) install
	cd mouse       && $(MAKE) install
	cd pic16f627   && $(MAKE) install
	cd pic16f648a  && $(MAKE) install
	cd pic18f1320  && $(MAKE) install
	cd pic18f2550  && $(MAKE) install
	cd pic18f25k22 && $(MAKE) install
	cd pic30       && $(MAKE) install
	cd rkp28sb     && $(MAKE) install
	cd test        && $(MAKE) install
	cd velleman    && $(MAKE) install

uninstall:
	cd debug       && $(MAKE) uninstall
	cd include     && $(MAKE) uninstall
	cd microchip   && $(MAKE) uninstall
	cd mouse       && $(MAKE) uninstall
	cd pic16f627   && $(MAKE) uninstall
	cd pic16f648a  && $(MAKE) uninstall
	cd pic18f1320  && $(MAKE) uninstall
	cd pic18f2550  && $(MAKE) uninstall
	cd pic18f25k22 && $(MAKE) uninstall
	cd pic30       && $(MAKE) uninstall
	cd rkp28sb     && $(MAKE) uninstall
	cd test        && $(MAKE) uninstall
	cd velleman    && $(MAKE) uninstall

clean:
	cd debug       && $(MAKE) clean
	cd include     && $(MAKE) clean
	cd microchip   && $(MAKE) clean
	cd mouse       && $(MAKE) clean
	cd pic16f627   && $(MAKE) clean
	cd pic16f648a  && $(MAKE) clean
	cd pic18f1320  && $(MAKE) clean
	cd pic18f2550  && $(MAKE) clean
	cd pic18f25k22 && $(MAKE) clean
	cd pic30       && $(MAKE) clean
	cd rkp28sb     && $(MAKE) clean
	cd test        && $(MAKE) clean
	cd velleman    && $(MAKE) clean
	rm -f *~
