#!/bin/sh
#
# Copyright (C) 2005-2014 Darron Broad
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
#
#    This product includes software developed by Darron Broad.
#
# 4. Neither the name of Darron Broad nor the names of any
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
# Darron Broad BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
INDENT="/usr/bin/indent"

if test $# -ne 1; then
	echo "missing arg"
	exit 1
fi

TMPFILE=`mktemp /tmp/indent.XXXXXXXXXX`

cat $1 | tr -d '\r' | $INDENT -orig -d0 -l128 -bl -blf -bls -bli0 -npcs -nce -nbbb -nbc -nbap -nbad -ncs -di0 -nbc -ut -i8 -nfc1 -nfca -c1 | sed 's/const const/const/' > $TMPFILE

if test -s $TMPFILE; then
	cp $TMPFILE $1
	rm -f $TMPFILE
fi

exit 0
