#
# Copyright (C) 2005-2014 Darron Broad
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# 3. Neither the name `Darron Broad' nor the names of any contributors
#    may be used to endorse or promote products derived from this
#    software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

build:
	$(MAKE) -f gpasm.mk build
	$(MAKE) -f dsPIC30F1010.mk build
	$(MAKE) -f dsPIC30F4013.mk build
	$(MAKE) -f dsPIC33EP128GP502.mk build
	$(MAKE) -f dsPIC33FJ06GS101A.mk build
	$(MAKE) -f dsPIC33FJ128GP802.mk build
	$(MAKE) -f dsPIC33FJ16GS502.mk build
	$(MAKE) -f dsPIC33FJ32MC102.mk build
	$(MAKE) -f PIC24F04KA201.mk build
	$(MAKE) -f PIC24F16KL402.mk build
	$(MAKE) -f PIC24FJ128GA202.mk build
	$(MAKE) -f PIC24FJ128GB202.mk build
	$(MAKE) -f PIC24FJ16MC101.mk build
	$(MAKE) -f PIC24FJ64GA002.mk build
	$(MAKE) -f PIC24FJ64GB002.mk build
	$(MAKE) -f PIC24FV32KA302.mk build
	$(MAKE) -f PIC24HJ128GP502.mk build
	$(MAKE) -f PIC32MX150F128B.mk build
	$(MAKE) -f PIC32MX170F256B.mk build
	$(MAKE) -f PIC32MX250F128B.mk build
	$(MAKE) -f PIC32MX795F512H.mk build

install:build
	$(MAKE) -f gpasm.mk install
	$(MAKE) -f dsPIC30F1010.mk install
	$(MAKE) -f dsPIC30F4013.mk install
	$(MAKE) -f dsPIC33EP128GP502.mk install
	$(MAKE) -f dsPIC33FJ06GS101A.mk install
	$(MAKE) -f dsPIC33FJ128GP802.mk install
	$(MAKE) -f dsPIC33FJ16GS502.mk install
	$(MAKE) -f dsPIC33FJ32MC102.mk install
	$(MAKE) -f PIC24F04KA201.mk install
	$(MAKE) -f PIC24F16KL402.mk install
	$(MAKE) -f PIC24FJ128GA202.mk install
	$(MAKE) -f PIC24FJ128GB202.mk install
	$(MAKE) -f PIC24FJ16MC101.mk install
	$(MAKE) -f PIC24FJ64GA002.mk install
	$(MAKE) -f PIC24FJ64GB002.mk install
	$(MAKE) -f PIC24FV32KA302.mk install
	$(MAKE) -f PIC24HJ128GP502.mk install
	$(MAKE) -f PIC32MX150F128B.mk install
	$(MAKE) -f PIC32MX170F256B.mk install
	$(MAKE) -f PIC32MX250F128B.mk install
	$(MAKE) -f PIC32MX795F512H.mk install

uninstall:
	$(MAKE) -f gpasm.mk uninstall
	$(MAKE) -f dsPIC30F1010.mk uninstall
	$(MAKE) -f dsPIC30F4013.mk uninstall
	$(MAKE) -f dsPIC33EP128GP502.mk uninstall
	$(MAKE) -f dsPIC33FJ06GS101A.mk uninstall
	$(MAKE) -f dsPIC33FJ128GP802.mk uninstall
	$(MAKE) -f dsPIC33FJ16GS502.mk uninstall
	$(MAKE) -f dsPIC33FJ32MC102.mk uninstall
	$(MAKE) -f PIC24F04KA201.mk uninstall
	$(MAKE) -f PIC24F16KL402.mk uninstall
	$(MAKE) -f PIC24FJ128GA202.mk uninstall
	$(MAKE) -f PIC24FJ128GB202.mk uninstall
	$(MAKE) -f PIC24FJ16MC101.mk uinstall
	$(MAKE) -f PIC24FJ64GA002.mk uinstall
	$(MAKE) -f PIC24FJ64GB002.mk uinstall
	$(MAKE) -f PIC24FV32KA302.mk uinstall
	$(MAKE) -f PIC24HJ128GP502.mk uinstall
	$(MAKE) -f PIC32MX150F128B.mk uninstall
	$(MAKE) -f PIC32MX170F256B.mk uninstall
	$(MAKE) -f PIC32MX250F128B.mk uninstall
	$(MAKE) -f PIC32MX795F512H.mk uninstall

clean:
	$(MAKE) -f gpasm.mk clean
	$(MAKE) -f dsPIC30F1010.mk clean
	$(MAKE) -f dsPIC30F4013.mk clean
	$(MAKE) -f dsPIC33EP128GP502.mk clean
	$(MAKE) -f dsPIC33FJ06GS101A.mk clean
	$(MAKE) -f dsPIC33FJ128GP802.mk clean
	$(MAKE) -f dsPIC33FJ16GS502.mk clean
	$(MAKE) -f dsPIC33FJ32MC102.mk clean
	$(MAKE) -f PIC24F04KA201.mk clean
	$(MAKE) -f PIC24F16KL402.mk clean
	$(MAKE) -f PIC24FJ128GA202.mk clean
	$(MAKE) -f PIC24FJ128GB202.mk clean
	$(MAKE) -f PIC24FJ16MC101.mk clean
	$(MAKE) -f PIC24FJ64GA002.mk clean
	$(MAKE) -f PIC24FJ64GB002.mk clean
	$(MAKE) -f PIC24FV32KA302.mk clean
	$(MAKE) -f PIC24HJ128GP502.mk clean
	$(MAKE) -f PIC32MX150F128B.mk clean
	$(MAKE) -f PIC32MX170F256B.mk clean
	$(MAKE) -f PIC32MX250F128B.mk clean
	$(MAKE) -f PIC32MX795F512H.mk clean
